name: myemes
favicon: null
layout_spectrum: 0.93741
typography_spectrum: 0.28437
title: Emes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030406'
    - '#d0893f'
    - '#f1c486'
    - '#83531f'
    - '#5d3110'
  brandStrength: 0.6413671458140016
  lightness: 0.8416057866998017
  saturation: 0.125
  rhythmicContrast: 0.7081959799397737
purpose: []
