name: myemes
favicon: null
layout_spectrum: 0.9817334329709411
typography_spectrum: 0.6080712294206023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6413671458140016
  lightness: 0.8416057866998017
  saturation: 0.1975944882724434
  rhythmicContrast: 0.7081959799397737
purpose: []
